const DIGEST_MARKS={"week-ahead-cpi-earnings-20260712":[["23.4% 至 23.7%","data"],["距离 6 月初纪录收盘不足 1%","data"],["高估值","strong"],["长端收益率挤压","mark"]],"oil-inflation-volatility-20260712":[["约 6%","data"],["接近 78 美元","data"],["共同变量","strong"],["同向恶化","underline"]],"imf-growth-inflation-20260712":[["3.0%","data"],["4.7%","data"],["高度依赖 Hormuz 渐进恢复","strong"],["实际收入与融资成本压力","mark"]],"apple-broadcom-us-chips-20260712":[["超过 300 亿美元","data"],["超过 150 亿颗","data"],["需求确定性","strong"],["成熟且高量的通信部件","mark"]],"tsmc-pricing-capex-20260712":[["gross margin","mark"],["CoWoS","data"],["价格权","strong"],["海外 fab 又持续抬高成本","underline"]],"atlas-worldcup-deployment-20260712":[["2028 年","data"],["专用 radio communication","mark"],["通信鲁棒性","strong"],["一次受控展示无法证明","underline"]],"dexterous-hands-20260712":[["约月产 5000 只灵巧手","data"],["数据质量和 contact robustness","strong"],["长尾物体、接触不确定性与维护","underline"],["force/tactile feedback","mark"]],"freddy-influencer-authenticity-20260712":[["真实性实验","strong"],["provenance 问题","mark"],["未确认其真实身份","underline"],["第二轮流量","data"]],"streaming-july13-19-20260712":[["7 月 13–19 日","data"],["marquee title","strong"],["重复访问","mark"],["无法提前验证观看量","underline"]],"apple-tv-pvod-chart-20260712":[["榜单前列","data"],["愿意单独付费","strong"],["清晰题材、院线余热和已知 IP","mark"],["未公开绝对交易量","underline"]]};
const USER_READS={};
const USER_ACTIONS={};
(function(){
  function injectStyles(){
    if(document.getElementById('editorial-mark-styles'))return;
    const style=document.createElement('style');
    style.id='editorial-mark-styles';
    style.textContent=`.digest-reader.editorial-marks{font-family:var(--serif);font-size:16px;line-height:1.92;color:#241e16;background:linear-gradient(180deg,rgba(255,253,248,.94),rgba(246,239,225,.70));border-left:4px solid var(--gold);border-radius:15px;padding:17px 18px}.digest-reader.editorial-marks .digest-lede{font-size:18px;line-height:1.66;font-weight:900}.ed-strong{font-weight:880}.ed-mark{font-weight:780;background:linear-gradient(transparent 66%,rgba(225,185,107,.28) 0)}.ed-underline{text-decoration:underline}.ed-data{font-family:var(--mono);font-weight:780;background:rgba(184,129,47,.10);border-radius:6px;padding:.01em .22em}`;
    document.head.appendChild(style);
  }
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
  function cssEscape(s){return String(s).replace(/(["\\])/g,'\\$1');}
  function applyOne(html,phrase,type){const safe=esc(phrase);if(!html.includes(safe))return html;const cls={strong:'ed-strong',mark:'ed-mark',underline:'ed-underline',data:'ed-data'}[type]||'ed-strong';return html.replace(safe,`<span class="${cls}">${safe}</span>`);}
  function buildDigest(id,text){const marks=DIGEST_MARKS[id]||[];const m=text.match(/^(.+?[。！？.!?])(.+)$/s);const lead=m?m[1]:text.slice(0,90);const rest=m?m[2].trim():text.slice(90).trim();let leadHtml=esc(lead),bodyHtml=esc(rest);marks.forEach(([phrase,type])=>{leadHtml=applyOne(leadHtml,phrase,type);bodyHtml=applyOne(bodyHtml,phrase,type);});const paragraphs=bodyHtml.split(/(?<=[。！？])\s*/).filter(Boolean).map(p=>`<p>${p}</p>`).join('');return `<div class="digest-reader editorial-marks" data-editorial-marked="1"><p class="digest-lede">${leadHtml}</p><div class="digest-body">${paragraphs}</div></div>`;}
  function run(){injectStyles();if(typeof STORIES==='undefined')return false;const feed=document.getElementById('feed');if(!feed||!feed.children.length)return false;let changed=false;STORIES.forEach(function(s){const article=document.querySelector(`.story-row[data-id="${cssEscape(s.id)}"]`);if(!article)return;const panel=article.querySelector('.analysis-panel');if(panel){const old=panel.querySelector('.digest,.digest-reader:not([data-editorial-marked="1"])');if(old){old.outerHTML=buildDigest(s.id,s.digest);changed=true;}}});return changed;}
  document.addEventListener('DOMContentLoaded',function(){let tries=0;const timer=setInterval(function(){tries++;if(run()||tries>30)clearInterval(timer);},150);const feed=document.getElementById('feed');if(feed&&window.MutationObserver){new MutationObserver(function(){run();}).observe(feed,{childList:true,subtree:true});}});
})();