const DIGEST_MARKS={"week-ahead-cpi-banks-tsmc-20260713":[["约 23.4%","data"],["证据密集区","strong"],["达标但未上修","underline"]],"oil-inflation-centralbanks-20260713":[["约 6%","data"],["共同变量","strong"],["同向恶化","underline"]],"imf-growth-fragility-20260713":[["3.0%","data"],["4.7%","data"],["联合假设","mark"]],"micron-us-wafer-chain-20260713":[["超过 2500 亿美元","data"],["十年供货协议","strong"],["供给确定性","mark"]],"helium-chipmaking-squeeze-20260713":[["临时暂停 helium 出口","data"],["隐性约束","strong"],["工业气体与超高纯材料","mark"]],"atlas-field-constraints-20260713":[["2028 年","data"],["无线拥塞","strong"],["一次经过准备的公开展示无法证明","underline"]],"dexterous-hands-data-layer-20260713":[["月产约 5000 只灵巧手","data"],["tactile data 与 contact robustness","strong"],["单次流畅 demo 的边际价值持续下降","underline"]],"worldcup-y2k-fashion-20260713":[["7 月 12 日","data"],["nostalgia 正在重写球迷身份","strong"],["跨圈层","mark"]],"moana-live-action-boxoffice-20260713":[["全球开画约 9500 万美元","data"],["制作成本约 2.5 亿美元","data"],["发行节奏与观众饱和","strong"]],"streaming-menu-july13-19-20260713":[["7 月 13–19 日","data"],["单个 marquee title","strong"],["内容库总量对续订的解释力继续下降","underline"]]};
const USER_READS={};
const USER_ACTIONS={};
(function(){
  function injectStyles(){
    if(document.getElementById('editorial-mark-styles'))return;
    const style=document.createElement('style');
    style.id='editorial-mark-styles';
    style.textContent=`.digest-reader.editorial-marks{font-family:var(--serif);font-size:16px;line-height:1.92;color:#241e16;background:linear-gradient(180deg,rgba(255,253,248,.94),rgba(246,239,225,.70));border-left:4px solid var(--gold);border-radius:15px;padding:17px 18px}.digest-reader.editorial-marks .digest-lede{font-size:18px;line-height:1.66;font-weight:900}.ed-strong{font-weight:880}.ed-mark{font-weight:780;background:linear-gradient(transparent 66%,rgba(225,185,107,.28) 0)}.ed-underline{text-decoration:underline}.ed-data{font-family:var(--mono);font-weight:780;background:rgba(184,129,47,.10);border-radius:6px;padding:.01em .22em}`;
    document.head.appendChild(style);
  }
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
  function cssEscape(s){return String(s).replace(/(["\\])/g,'\\$1');}
  function applyOne(html,phrase,type){const safe=esc(phrase);if(!html.includes(safe))return html;const cls={strong:'ed-strong',mark:'ed-mark',underline:'ed-underline',data:'ed-data'}[type]||'ed-strong';return html.replace(safe,`<span class="${cls}">${safe}</span>`);}
  function buildDigest(id,text){const marks=DIGEST_MARKS[id]||[];const m=text.match(/^(.+?[。！？.!?])(.+)$/s);const lead=m?m[1]:text.slice(0,90);const rest=m?m[2].trim():text.slice(90).trim();let leadHtml=esc(lead),bodyHtml=esc(rest);marks.forEach(([phrase,type])=>{leadHtml=applyOne(leadHtml,phrase,type);bodyHtml=applyOne(bodyHtml,phrase,type);});const paragraphs=bodyHtml.split(/(?<=[。！？])\s*/).filter(Boolean).map(p=>`<p>${p}</p>`).join('');return `<div class="digest-reader editorial-marks" data-editorial-marked="1"><p class="digest-lede">${leadHtml}</p><div class="digest-body">${paragraphs}</div></div>`;}
  function run(){injectStyles();if(typeof STORIES==='undefined')return false;const feed=document.getElementById('feed');if(!feed||!feed.children.length)return false;let changed=false;STORIES.forEach(function(s){const article=document.querySelector(`.story-row[data-id="${cssEscape(s.id)}"]`);if(!article)return;const panel=article.querySelector('.analysis-panel');if(panel){const old=panel.querySelector('.digest,.digest-reader:not([data-editorial-marked="1"])');if(old){old.outerHTML=buildDigest(s.id,s.digest);changed=true;}}});return changed;}
  document.addEventListener('DOMContentLoaded',function(){let tries=0;const timer=setInterval(function(){tries++;if(run()||tries>30)clearInterval(timer);},150);const feed=document.getElementById('feed');if(feed&&window.MutationObserver){new MutationObserver(function(){run();}).observe(feed,{childList:true,subtree:true});}});
})();
