const DIGEST_MARKS={"week-ahead-cpi-earnings-20260711":[["23.4% 至 23.7%","data"],["距离 6 月初的纪录收盘不足 1%","data"],["高估值仍可承受","strong"],["盈利只达预期","mark"]],"market-calm-oil-20260711":[["上涨 14%","data"],["4.561%","data"],["窄平衡","strong"],["供应中断仍可管理","underline"]],"sterling-boe-20260711":[["1.345 美元","data"],["85.18 便士","data"],["较高利率维持更久","strong"],["缓冲进口价格","mark"]],"micron-us-supply-chain-20260711":[["超过 2500 亿美元","data"],["约 220 亿美元订单","data"],["产能 + 材料 + 长约","strong"],["硅晶圆","mark"]],"tsmc-bottleneck-pricing-20260711":[["AI chip supply chain 的瓶颈","strong"],["gross margin","mark"],["海外 fab 又持续推高成本","underline"],["下周四","data"]],"unitree-ipo-20260711":[["42 亿元人民币","data"],["至少 4045 万股","data"],["经营质量考核","strong"],["质保成本和客户复购","mark"]],"dexterous-hands-20260711":[["约月产 5000 只灵巧手","data"],["数据质量与接触控制","strong"],["长尾物体、接触不确定性和维护成本","underline"],["force/tactile feedback","mark"]],"worldcup-country-roads-20260711":[["比赛之外的 30 秒","data"],["可二创的情绪资产","strong"],["仪式和二创素材正在形成","mark"],["不能直接折算为版权收入","underline"]],"streaming-july13-19-20260711":[["7 月 13–19 日","data"],["7 月 17 日","data"],["周末大标题","strong"],["反复打开应用","mark"]],"streaming-subscription-value-20260711":[["约 50 美元预算","data"],["按月轮换","strong"],["subscription fatigue","mark"],["未使用统一的观看时长、退订率或 ARPU 数据","underline"]]};
const USER_READS={};
const USER_ACTIONS={};
(function(){
  function injectStyles(){
    if(document.getElementById('editorial-mark-styles'))return;
    const style=document.createElement('style');
    style.id='editorial-mark-styles';
    style.textContent=`.digest-reader.editorial-marks{font-family:var(--serif);font-size:16px;line-height:1.92;color:#241e16;background:linear-gradient(180deg,rgba(255,253,248,.94),rgba(246,239,225,.70));border-left:4px solid var(--gold);border-radius:15px;padding:17px 18px}.digest-reader.editorial-marks .digest-lede{font-size:18px;line-height:1.66;font-weight:900}.ed-strong{font-weight:880}.ed-mark{font-weight:780;background:linear-gradient(transparent 66%,rgba(225,185,107,.28) 0)}.ed-underline{text-decoration:underline}.ed-data{font-family:var(--mono);font-weight:780;background:rgba(184,129,47,.10);border-radius:6px;padding:.01em .22em}`;
    document.head.appendChild(style);
  }
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
  function cssEscape(s){return String(s).replace(/(["\\])/g,'\\$1');}
  function applyOne(html,phrase,type){const safe=esc(phrase);if(!html.includes(safe))return html;const cls={strong:'ed-strong',mark:'ed-mark',underline:'ed-underline',data:'ed-data'}[type]||'ed-strong';return html.replace(safe,`<span class="${cls}">${safe}</span>`);}
  function buildDigest(id,text){const marks=DIGEST_MARKS[id]||[];const m=text.match(/^(.+?[。！？.!?])(.+)$/s);const lead=m?m[1]:text.slice(0,90);const rest=m?m[2].trim():text.slice(90).trim();let leadHtml=esc(lead),bodyHtml=esc(rest);marks.forEach(([phrase,type])=>{leadHtml=applyOne(leadHtml,phrase,type);bodyHtml=applyOne(bodyHtml,phrase,type);});const paragraphs=bodyHtml.split(/(?<=[。！？])\s*/).filter(Boolean).map(p=>`<p>${p}</p>`).join('');return `<div class="digest-reader editorial-marks" data-editorial-marked="1"><p class="digest-lede">${leadHtml}</p><div class="digest-body">${paragraphs}</div></div>`;}
  function run(){injectStyles();if(typeof STORIES==='undefined')return false;const feed=document.getElementById('feed');if(!feed||!feed.children.length)return false;let changed=false;STORIES.forEach(function(s){const article=document.querySelector(`.story-row[data-id="${cssEscape(s.id)}"]`);if(!article)return;const panel=article.querySelector('.analysis-panel');if(panel){const old=panel.querySelector('.digest,.digest-reader:not([data-editorial-marked="1"])');if(old){old.outerHTML=buildDigest(s.id,s.digest);changed=true;}}});return changed;}
  document.addEventListener('DOMContentLoaded',function(){let tries=0;const timer=setInterval(function(){tries++;if(run()||tries>30)clearInterval(timer);},150);const feed=document.getElementById('feed');if(feed&&window.MutationObserver){new MutationObserver(function(){run();}).observe(feed,{childList:true,subtree:true});}});
})();
